apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop-1
  namespace: argocd
spec:
  project: default
  destination:
    namespace: eks-bp-ns
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: od-artefacts/65aa26821fb5a879de0e1edc/appBlueprints/eshop-1/v0
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true